sonar.projectKey=arckium-tickets-frontend
sonar.projectName=Arckium Tickets Frontend
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.sourceEncoding=UTF-8

sonar.test.inclusions=**/*.{test,spec}.{js,jsx,ts,tsx}
sonar.exclusions=**/*.{test,spec}.{js,jsx,ts,tsx},**/main.jsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=**/*.{test,spec}.{js,jsx},**/main.jsx,**/data/**
