apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-backend
  namespace: arckium
  labels:
    app: tickets-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets-backend
  template:
    metadata:
      labels:
        app: tickets-backend
    spec:
      containers:
        - name: backend
          image: docker.io/feresadouani10/tickets-backend:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-config
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
