apiVersion: v1
kind: Service
metadata:
  name: tickets-backend
  namespace: arckium
  labels:
    app: tickets-backend
spec:
  type: NodePort
  selector:
    app: tickets-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30300
      protocol: TCP
